Repository joaoveasey/projeto-pets-react, pull requests merged in 2024-06, with the labels that each got.

#33 Criação da dogDetails. jsx e dogDetails.module.css
  my-react-app/src/assets/ELEMENTS.png
  my-react-app/src/assets/descriptionIcon.png
  my-react-app/src/assets/patacachorro.png
  my-react-app/src/pages/DogDetails/dogDetails.jsx
  my-react-app/src/pages/DogDetails/dogDetails.module.css
  my-react-app/src/pages/DogPage/dogPage.jsx
  my-react-app/src/pages/DogPage/dogPage.module.css
  my-react-app/src/pages/Home/home.jsx
  my-react-app/src/pages/Home/home.module.css
  my-react-app/src/routes.jsx
Labels: enhancement

#34 Atualização home.module.css
  my-react-app/src/pages/Home/home.module.css
Labels: bug

#35 criação dos arquivos jsx.css da pagina duvidas
  my-react-app/public/Contato.png
  my-react-app/public/PolygonClosed.png
  my-react-app/public/PolygonOpened.png
  my-react-app/src/pages/About/About.Module.css
  my-react-app/src/pages/About/about.jsx
  my-react-app/src/pages/Doubts/Doubts.Button.css
  my-react-app/src/pages/Doubts/doubts.jsx
  my-react-app/src/pages/Doubts/doubts.module.css
  my-react-app/src/pages/Tips/Tips.Module.css
  my-react-app/src/pages/Tips/tips.jsx
  my-react-app/src/routes.jsx
Labels: bug, enhancement

#36 Revert "criação dos arquivos jsx.css da pagina duvidas "
  my-react-app/public/Contato.png
  my-react-app/public/PolygonClosed.png
  my-react-app/public/PolygonOpened.png
  my-react-app/src/pages/About/About.Module.css
  my-react-app/src/pages/About/about.jsx
  my-react-app/src/pages/Doubts/Doubts.Button.css
  my-react-app/src/pages/Doubts/doubts.jsx
  my-react-app/src/pages/Doubts/doubts.module.css
  my-react-app/src/pages/Tips/Tips.Module.css
  my-react-app/src/pages/Tips/tips.jsx
  my-react-app/src/routes.jsx
Labels: bug, enhancement

#37 criação de novas páginas (Recuperar Senha, Dúvidas, Sobre, e Dicas)
  my-react-app/public/Contato.png
  my-react-app/public/PolygonClosed.png
  my-react-app/public/PolygonOpened.png
  my-react-app/src/pages/About/About.Module.css
  my-react-app/src/pages/About/about.jsx
  my-react-app/src/pages/Doubts/Doubts.Button.css
  my-react-app/src/pages/Doubts/doubts.jsx
  my-react-app/src/pages/Doubts/doubts.module.css
  my-react-app/src/pages/Login/login.jsx
  my-react-app/src/pages/RecoverPassword/recoverPassword.jsx
  my-react-app/src/pages/RecoverPassword/recoverPassword.module.css
  my-react-app/src/pages/Tips/Tips.Module.css
  my-react-app/src/pages/Tips/tips.jsx
  my-react-app/src/routes.jsx
Labels: enhancement

#41 criação da autenticação de usuário e navegação do usuário logado/cadastrado na plataforma
  my-react-app/src/App.jsx
  my-react-app/src/components/Navbar/Navbar.jsx
  my-react-app/src/components/Navbar/Navbar.module.css
  my-react-app/src/components/Navbar/img/PolygonOpened.png
  my-react-app/src/components/Navbar/img/user.png
  my-react-app/src/context/AuthContext.jsx
  my-react-app/src/firebase/config.jsx
  my-react-app/src/hooks/userAuthentication.jsx
  my-react-app/src/main.jsx
  my-react-app/src/pages/DogDetails/dogDetails.jsx
  my-react-app/src/pages/Home/home.jsx
  my-react-app/src/pages/Login/login.jsx
  my-react-app/src/routes.jsx
Labels: bug, enhancement

#42 Criação do perfil do usuário e da responsividade
  my-react-app/package-lock.json
  my-react-app/package.json
  my-react-app/src/assets/PessoaUsuario.png
  my-react-app/src/assets/email.png
  my-react-app/src/assets/perfilUsuario.png
  my-react-app/src/assets/phone.png
  my-react-app/src/components/Footer/Footer.module.css
  my-react-app/src/pages/DogDetails/dogDetails.jsx
  my-react-app/src/pages/DogDetails/dogDetails.module.css
  my-react-app/src/pages/DogPage/dogPage.jsx
  my-react-app/src/pages/DogPage/dogPage.module.css
  my-react-app/src/pages/Home/home.module.css
  my-react-app/src/pages/UserPage/userPage.jsx
  my-react-app/src/pages/UserPage/userPage.module.css
Labels: enhancement

#54 Criação da Responsividade e Ajuste na Estilização
  my-react-app/src/components/Footer/Footer.module.css
  my-react-app/src/components/Navbar/Navbar.jsx
  my-react-app/src/components/Navbar/Navbar.module.css
  my-react-app/src/pages/About/About.Module.css
  my-react-app/src/pages/DogDetails/dogDetails.module.css
  my-react-app/src/pages/Doubts/Doubts.Button.css
  my-react-app/src/pages/Doubts/doubts.jsx
  my-react-app/src/pages/Doubts/doubts.module.css
  my-react-app/src/pages/Home/home.module.css
  my-react-app/src/pages/Login/login.module.css
  my-react-app/src/pages/RecoverPassword/recoverPassword.module.css
  my-react-app/src/pages/Register/register.module.css
  my-react-app/src/pages/Tips/Tips.Module.css
  my-react-app/src/pages/Tips/tips.jsx
  my-react-app/src/pages/UserPage/userPage.module.css
Labels: enhancement

#60 Implementação login/autentição facebook e github
  my-react-app/src/hooks/userAuthentication.jsx
  my-react-app/src/pages/Login/login.jsx
Labels: enhancement

#67 Estilização dos links de Navegação e adição de ícones nos Menus de Navegação
  my-react-app/package-lock.json
  my-react-app/package.json
  my-react-app/src/components/Navbar/Navbar.jsx
  my-react-app/src/components/Navbar/Navbar.module.css
  my-react-app/src/pages/Doubt/doubt.jsx
Labels: enhancement

#62 12. Adicionar Contagem de Caracteres em Textarea
  my-react-app/src/pages/Doubt/doubt.jsx
  my-react-app/src/pages/Doubt/doubt.module.css
Labels: enhancement

#72 Inclusão de detalhes sobre os membros da equipe.
  my-react-app/public/cesar.jpg
  my-react-app/public/enzo.jpg
  my-react-app/public/nicolas.jpg
  my-react-app/public/pedrin.jpg
  my-react-app/public/veasey.jpg
  my-react-app/src/pages/About/About.Module.css
  my-react-app/src/pages/About/about.jsx
Labels: enhancement

#73 Implementar Sistema de Upload de Imagens no Perfil de Usuário e Adicionar Upload de Arquivos com Firebase Storage
  my-react-app/package-lock.json
  my-react-app/package.json
  my-react-app/src/firebase/config.jsx
  my-react-app/src/pages/UserPage/userPage.jsx
  my-react-app/src/pages/UserPage/userPage.module.css
Labels: enhancement

#74 Task 34 - Implementar Página de Contato
  my-react-app/src/firebase/config.jsx
  my-react-app/src/pages/Doubt/doubt.jsx
Labels: enhancement

#76 Integração com Google Analytics
  my-react-app/package-lock.json
  my-react-app/package.json
  my-react-app/src/Analytics.js
  my-react-app/src/App.jsx
  my-react-app/src/main.jsx
Labels: enhancement

#79 26. Implementar Sistema de Avaliação de Produtos
  my-react-app/src/pages/DogDetails/dogDetails.jsx
  my-react-app/src/pages/DogDetails/dogDetails.module.css
Labels: enhancement

#78 10. Configurar CI/CD com GitHub Actions e Firebase Hosting
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  my-react-app/.firebase/hosting.ZGlzdA.cache
Labels: enhancement

#81 Implementação de Sistema de Compartilhamento de Conteúdo
  my-react-app/src/pages/DogDetails/ShareButtons.css
  my-react-app/src/pages/DogDetails/ShareButtons.jsx
  my-react-app/src/pages/DogDetails/dogDetails.jsx
  my-react-app/src/pages/DogDetails/dogDetails.module.css
Labels: enhancement

#84 Implementação de um sistema de comentários em tempo real usando Firebase Firestore
  my-react-app/src/App.jsx
  my-react-app/src/components/Comments/CommentForm.jsx
  my-react-app/src/components/Comments/CommentForm.module.css
  my-react-app/src/components/Comments/CommentList.jsx
  my-react-app/src/components/Comments/CommentList.module.css
  my-react-app/src/components/Navbar/Navbar.jsx
  my-react-app/src/pages/CommentsPage/commentsPage.jsx
  my-react-app/src/pages/CommentsPage/commentsPage.module.css
Labels: enhancement

#88 Implementação de testes com cypress para geral, login, produtos
  my-react-app/cypress.config.js
  my-react-app/cypress/fixtures/example.json
  my-react-app/cypress/integration/app.spec.js
  my-react-app/cypress/integration/dogDetails.spec.js
  my-react-app/cypress/integration/login.spec.js
  my-react-app/cypress/support/commands.js
  my-react-app/cypress/support/e2e.js
  my-react-app/package-lock.json
  my-react-app/package.json
Labels: enhancement

#90 Implementação de Sistema de Avaliação de Conteúdo
  my-react-app/src/assets/heart-empty.png
  my-react-app/src/assets/heart-full.png
  my-react-app/src/pages/DogPage/dogPage.jsx
  my-react-app/src/pages/DogPage/dogPage.module.css
Labels: enhancement

#92 Implementação de Sistema de Feedback de Usuário
  my-react-app/src/pages/Tips/Tips.Module.css
  my-react-app/src/pages/Tips/tips.jsx
Labels: enhancement

#95 Adicionar Login com Facebook
  my-react-app/src/hooks/userAuthentication.jsx
  my-react-app/src/pages/Login/login.jsx
Labels: enhancement

#98 Adicionar Autenticação com GitHub
  my-react-app/src/hooks/userAuthentication.jsx
  my-react-app/src/pages/Login/login.jsx
Labels: enhancement

#99 Implementar Testes de Integração com Cypress
  my-react-app/cypress.config.js
  my-react-app/cypress/fixtures/example.json
  my-react-app/cypress/integration/app.spec.js
  my-react-app/cypress/integration/login.spec.js
  my-react-app/cypress/support/commands.js
  my-react-app/cypress/support/e2e.js
Labels: enhancement

#102 Implementar Testes de Integração com Cypress para o Sistema de Avaliação de Produtos
  my-react-app/cypress/integration/DogDetails.spec.js
Labels: enhancement

#103 Implementar Autenticação de Dois Fatores
  my-react-app/src/hooks/userAuthentication.jsx
Labels: enhancement

#104 Implementação Dark Mode
  my-react-app/src/components/Navbar/Navbar.jsx
  my-react-app/src/components/Navbar/Navbar.module.css
  my-react-app/src/context/ThemeContext.jsx
  my-react-app/src/index.css
  my-react-app/src/main.jsx
  my-react-app/src/styles/global.css
Labels: enhancement
